return {
  ["workshop-1392778117"]={
    configuration_options={
      AgronExchangeTime=0,
      AgronRechargeTime=0,
      AutoStackedLoot=false,
      BackCubChance=0.5,
      BetterCookBook=true,
      BiggerWWBox=true,
      DigestedItemMsg=true,
      DressUp=true,
      FlowerWeaponsChance=0.03,
      FoliageathChance=0.01,
      HiddenUpdateTimes=20,
      Language="chinese",
      LilyBushSpacing=1,
      ModTerrorShield=true,
      MouseInfo=1,
      OrchidBushSpacing=2,
      PhoenixBattleDifficulty=2,
      PhoenixRebirthCycle=7200,
      RefractedUpdateTimes=14,
      RevolvedUpdateTimes=10,
      RoseBushSpacing=1,
      ShieldExchangeTime=0,
      ShieldRechargeTime=0,
      ShyCoreFruits=1,
      ShyCoreGrowth=1,
      SimmerUpdateTimes=20,
      SivFeaDamage=26,
      SivFeaHealthCost=1.5,
      SivFeaThrowedNum=5,
      SivSolToMedal=true,
      SivingRootTex=1,
      SoulBookHealMult=1,
      TechUnlock="prototyper",
      TissueBerriesChance=0.01,
      TissueCactusChance=0.05,
      TissueLightbulbChance=0.008,
      Title="",
      TransTimeCrop=1,
      TransTimeSpec=1,
      WorldSwordLimitation=false,
      X_growthTime=1,
      X_overripeTime=1,
      X_pestRisk=0.007 
    },
    enabled=true 
  },
  ["workshop-1651623054"]={
    configuration_options={
      ddon=true,
      hbcolor="dynamic",
      hblength=10,
      hbpos=1,
      hbstyle="heart",
      value=true 
    },
    enabled=true 
  },
  ["workshop-1909182187"]={
    configuration_options={
      ["UI相关"]=false,
      containerdrag_setting=2,
      difficulty_switch=false,
      language_switch="ch",
      medal_goodmax_resources_multiple=0,
      medal_goodmid_resources_multiple=1,
      medal_inv_switch=true,
      medal_recipe_filter_switch=true,
      medal_shardskinholes_switch=false,
      medal_tag_optimization=1,
      medal_tech_lock=false,
      medal_tips_switch=true,
      medalequipslots_switch=true,
      medalpage_switch=false,
      show_medal_fx=true,
      transplant_switch=true,
      ["世界设置"]=false,
      ["信息展示"]=false,
      ["其他模组相关"]=false,
      ["基础设置"]=false 
    },
    enabled=true 
  },
  ["workshop-2119742489"]={
    configuration_options={
      ArrowsignEnable=true,
      CountdownEnable=true,
      HungerCost=0,
      Ownership=false,
      SanityCost=0 
    },
    enabled=true 
  },
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      Show_naughtiness=false,
      Show_range=true,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      item_info_mod=0,
      lang="chs",
      show_buddle_item=1,
      show_food_units=-1,
      show_fuel=true,
      show_fueled=3,
      show_nutrients=1,
      show_planar_resist=true,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-2941527805"]={
    configuration_options={
      [""]=false,
      AddServerTags=true,
      AutoAddtoServerMod=true,
      BBGOAT_chs=true,
      BugTracking=false,
      BugTrackingClient=true,
      Pigman_Strings=false,
      SMALL_TEXTURES=true,
      Test_function=false,
      ban_ignore_mod_out_of_date=true,
      check_mod=true,
      clear_font=true,
      mod_info_Chs=true,
      mod_main_Chs=true 
    },
    enabled=true 
  },
  ["workshop-3574405615"]={ configuration_options={ in_the_second_box=true }, enabled=true },
  ["workshop-3750536829"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=false,
      FIREOPTIONS=3,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=false,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=1 
    },
    enabled=true 
  } 
}